---
configure_mas_apps: yes

dotfiles_repo: https://github.com/thomasjpfan/dotfiles

default_user: thomasjpfan

dotfile_links:
  - src: ~/dotfiles/tmux/tmux.conf
    dst: ~/.tmux.conf
  - src: ~/dotfiles/tmux/tmux.conf.local
    dst: ~/.tmux.conf.local
  - src: ~/dotfiles/zshrc
    dst: ~/.zshrc
  - src: ~/dotfiles/spaceship-prompt/spaceship.zsh
    dst: ~/.zfunctions/prompt_spaceship_setup
  - src: ~/dotfiles/nvim-config/init.vim
    dst: ~/.config/nvim/init.vim
  - src: ~/dotfiles/git/gitconfig
    dst: ~/.gitconfig
  - src: ~/dotfiles/git/gitignore_global
    dst: ~/.gitignore_global
  - src: ~/dotfiles/condarc
    dst: ~/.condarc

homebrew_installed_packages:
  - tmux
  - jq
  - mosh
  - neovim
  - tree
  - wakeonlan
  - cmake
  - wget
  - git
  - mas
  - zsh
  - direnv
  - ctags
  - bat
  - pipx

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - firefox
  - google-chrome
  - docker
  - dropbox
  - alfred
  - appcleaner
  - bartender
  - carbon-copy-cloner
  - coderunner
  - dash
  - fork
  - forklift
  - nvalt
  - imageoptim
  - crunch
  - kaleidoscope
  - paw
  - postico
  - postgresql
  - pgtune
  - typinator
  - paintcode
  - bettertouchtool
  - turbo-boost-switcher

homebrew_cask_fonts:
  - font-fira-code
  - font-droid-sans-mono-for-powerline

mas_installed_apps:
  - { id: 824183456, name: "Affinity Photo" }
  - { id: 549083868, name: "Display Menu" }
  - { id: 1081413713, name: "GIF Brewery 3" }
  - { id: 462058435, name: "Microsoft Excel" }
  - { id: 427729297, name: "Runway" }
  - { id: 824171161, name: "Affinity Designer" }
  - { id: 462054704, name: "Microsoft Word" }
  - { id: 407963104, name: "Pixelmator" }
  #  - { id: 497799835, name: "Xcode" }
  - { id: 429449079, name: "Patterns" }
  - { id: 734258109, name: "Watchdog" }
  - { id: 961632517, name: "Be Focused Pro" }
  - { id: 969418666, name: "ColorSnapper2" }
  - { id: 586001240, name: "SQLPro for SQLite" }
  - { id: 403504866, name: "PCalc" }
  - { id: 924726344, name: "Deliveries" }
  - { id: 1055273043, name: "PDF Expert" }
  - { id: 686428787, name: "Duplicate Detective" }
  - { id: 562184107, name: "LanScan Pro" }
  - { id: 442168834, name: "SiteSucker" }
  - { id: 1354318707, name: "Core Tunnel" }
  - { id: 425424353, name: "The Unarchiver" }
  - { id: 494803304, name: "WiFi Explorer" }
  - { id: 419330170, name: "Moom" }
  - { id: 890031187, name: "Marked 2" }
  - { id: 409201541, name: "Pages" }
  - { id: 588726889, name: "ReadKit" }
  - { id: 979299240, name: "NetworkUtilityX" }
  - { id: 411643860, name: "DaisyDisk" }
  - { id: 409203825, name: "Numbers" }
  - { id: 866773894, name: "Quiver" }
  - { id: 409183694, name: "Keynote" }
  - { id: 1384080005, name: "Tweetbot" }
  - { id: 495152161, name: "Wizard" }
  - { id: 1440147259, name: "AdGuard for Safari" }
  - { id: 1143437985, name: "GoodTask" }
  - { id: 1319778037, name: "iStat Menus" }
