---
configure_mas_apps: yes

dotfiles_repo: https://github.com/thomasjpfan/dotfiles

default_user: thomasjpfan

dotfile_links:
  - src: ~/dotfiles/tmux/tmux.conf
    dst: ~/.tmux.conf
  - src: ~/dotfiles/tmux/tmux.conf.local
    dst: ~/.tmux.conf.local
  - src: ~/dotfiles/zshrc
    dst: ~/.zshrc
  - src: ~/dotfiles/spaceship-prompt/spaceship.zsh
    dst: ~/.zfunctions/prompt_spaceship_setup
  - src: ~/dotfiles/nvim-config/init.vim
    dst: ~/.config/nvim/init.vim
  - src: ~/dotfiles/git/gitconfig
    dst: ~/.gitconfig
  - src: ~/dotfiles/git/gitignore_global
    dst: ~/.gitignore_global
  - src: ~/dotfiles/condarc
    dst: ~/.condarc
  - src: ~/dotfiles/direnvrc
    dst: ~/.direnvrc
