- hosts: all
  connection: local

  vars_files:
    - config.yml

  tasks:
    - import_tasks: tasks/setup_homebrew.yml
    - import_tasks: tasks/setup_dotfiles.yml
    - import_tasks: tasks/setup_final.yml
